### ISSUE TITLE
World map

### ISSUE THREAD

**Issue by nadja-zlender** [elixir-europe-training/ELIXIR-TrP-Training-Metrics-Database-Tango#18]
User story
As an impact officer, I want to see up-to-date dashboard across all nodes, so that I can use these when creating impact stories.

- [x] I can see a world map with the location and counts of the training events.

**Comment by mihai-sysbio** [comment]
The map has been implement. With that as the single checkbox for this issue, I will close it. However, we should remember to user-test with the impact officer that they get all the charts/data they need (perhaps we need a general user-testing issue).
